language: fortran

env: FC=gfortran

addons:
  apt:
    packages: ['gfortran','liblapack-dev','libopenmpi-dev']

matrix:
  include:
  - os: osx
    before_install:
    - brew upgrade gcc > /dev/null
    - brew install lapack open-mpi > /dev/null

script:
- cd build
- gfortran getpath.f95 -o getpath